services:
  proxy-checker:
    build: proxy-checker
    container_name: proxy-checker
    expose:
      - "80"
    environment:
      # - VIRTUAL_HOST=david0403.site
      # - VIRTUAL_PORT=8000
      # - HTTP_PORT=8000
      - VIRTUAL_HOST=david0403.site
    restart: unless-stopped
    networks:
      - proxynet

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=david0403.site
      - VIRTUAL_PATH=/whoami
    networks:
      - proxynet

  proxy-path-checker:
    build: path-domain
    container_name: proxy-path-checker
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=david0403.site
      - VIRTUAL_PATH=/sub
    restart: unless-stopped
    networks:
      - proxynet

  nginx-proxy:
    depends_on:
      - proxy-checker
      - whoami
      - proxy-path-checker
    image: nginxproxy/nginx-proxy:alpine
    container_name: multi-domain-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html 
    restart: unless-stopped
    privileged: true
    networks:
      - proxynet

networks:
  proxynet:
    name: proxy_net_test
