services:
  a:
    build: a
    container_name: web-a
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=a.noboroto.id.vn
    restart: always
  
  calibre-web:
    image: lscr.io/linuxserver/calibre:arm64v8-latest
    container_name: calibre-deployed
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - VIRTUAL_HOST=calibre.noboroto.id.vn,calibre-ui.noboroto.id.vn
      - VIRTUAL_PORT=8081,8080
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - /home/david0403/Github/calibre-server/config:/config
    expose:
      - "8080"
      - "8081"
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true