services:
  proxy-checker:
    build: proxy-checker
    container_name: proxy-checker
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=a.noboroto.id.vn
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    depends_on: 
      - calibre-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d 
      - html:/usr/share/nginx/html 
    environment:
      - HTTPS_METHOD=noredirect
    restart: always
    privileged: true

  ssl-auto-renew:
    image: nginxproxy/acme-companion
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - env "DEFAULT_EMAIL=rockets-wrangle.0m@icloud.com"