services:
  a:
    build: a
    container_name: web-a
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=a.noboroto.id.vn
    restart: always

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    depends_on: 
      - calibre-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true