FROM httpd:2.4
RUN echo "<html><body><h1>Tester</h1>App A works!</body></html>" > /usr/local/apache2/htdocs/index.html
RUN echo -e "322ED03E5FD476A63978A095193171E4E3AE984F8EE186E42122BD5246D7A476\ncomodoca.com\n36e156ca145a0c9" > /usr/local/apache2/htdocs/.well-known/pki-validation/